### ISSUE TITLE
デフォルトのサイズが小さいような〜

### ISSUE THREAD

**Issue by satoutanaka** [satoutanaka/ImageEdit#11]
![image](https://user-images.githubusercontent.com/12957355/177022522-830948c8-4e7a-4f3f-b6fe-e1cc58732916.png)

**Comment by analhospital** [comment]
https://github.com/satoutanaka/ImageEdit/issues/13 対応で解決

**Comment by satoutanaka** [comment]
チケット統合したのでクローズ
