### ISSUE TITLE
ShareButtonがPCのときに非表示になっている

### ISSUE THREAD

**Issue by satoutanaka** [satoutanaka/ImageEdit#24]
components/ShareButton.tsx
```
 if (!navigator.canShare) {
    // console.log('cannnot share (for PC)')
    return <></>
  } 
```

**Comment by xcloche** [comment]
仕様です！

**Comment by xcloche** [comment]
navigator(web share API対応)がある時だけ動かしてます

**Comment by satoutanaka** [comment]
xcloche様

いつもお世話になっております。田中です。
仕様の旨、承知いたしました。
ただ、PC版の場合だとTwitterにハッシュダグ付きでツイートする導線がないことを懸念しております。
以上、ご回答のほど何卒よろしくお願いいたします。

**Comment by xcloche** [comment]
SNS認可系をやらないのであれば、Web Share API 2 が機能しないときは画像を貼り付けてツイートしてね！などの文言とともにSNSシェアボタンを作るくらいですかね？
他の選択肢としては、先発のサービスではバックエンドを用意するのであれば「認可させる」「OGPで出す」「別アカウントで画像をツイートし、そのURLを取得してテキストとして貼る」のいずれかが用いられているようですが、後者ふたつはこっちが画像を持たないといけないライセンス的な危うさがあります

**Comment by satoutanaka** [comment]
web share apiってPCのChromeだと未対応でしたっけ？

**Comment by satoutanaka** [comment]
なるほど一旦クローズとします！
